#######################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This work is made available under the terms of the
# Creative Commons Attribution 4.0 International (CC-BY-4.0) license,
# which is available at
# https://creativecommons.org/licenses/by/4.0/legalcode.
#
# SPDX-License-Identifier: CC-BY-4.0
#######################################################################
name: 'Validate Changes'
description: 'Action to validate detected changes in the repository as changes applicable to a Semantic Hub and to prepare an output.json file for the upload action'
inputs:
  ADDED:
    description: 'The changed files, detected by a previous action'
    default: "[]"
    required: false
  MODIFIED:
    description: 'The modified files, detected by a previous action'
    default: "[]"
    required: false
  REMOVED:
    description: 'The removed files, detected by a previous action'
    default: "[]"
    required: false
  IS_MAIN:
    description: 'A boolean value indicating whether the action operates on the main branch (True) or another branch (False)'
    default: false
    required: false  
runs:
  using: "node16"
  main: 'index.js'

