#######################################################################
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This work is made available under the terms of the
# Creative Commons Attribution 4.0 International (CC-BY-4.0) license,
# which is available at
# https://creativecommons.org/licenses/by/4.0/legalcode.
#
# SPDX-License-Identifier: CC-BY-4.0
#######################################################################
name: 'Upload Changes'
description: 'Action to upload detected changes to a Semantic Hub'
inputs:
  TOKEN:
    description: 'The token to acces the instance of the Semantic Hub'
    required: true
  SEMANTIC_HUB_URL:
    description: 'The url of the instance of the Semantic Hub'
    required: true
      
runs:
  using: "node16"
  main: 'index.js'

